[package]
name = "crack_sha1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12"}
sha-1 = "0.9"
hex = "0.4"